# Active Profile
spring.profiles.active=dev

# Common Configuration
spring.application.name=hermes

# Firebase Auth Configuration
firebase.web.api.key=AIzaSyBX95VRZdcXVJUZ5d7kmV-b1jY0jclTmyI

# VAPID Keys for Web Push
vapid.public.key=BDfOfuC9T_m0uV_iI8q97f8oW6z6h9F6c5R6G6U6S6h6I6T6S6h6I6T6S6h6I6T6S6h6I6T
# Note: Private key should be handled securely in production
vapid.private.key=X-R6G6U6S6h6I6T6S6h6I6T6S6h6I6T6S6h6I6T
vapid.subject=mailto:admin@hermes.com

# Jackson Configuration
spring.jackson.default-property-inclusion=non_null
spring.jackson.serialization.indent_output=true


# Gemini AI Configuration
gemini.api.key=AIzaSyCpUmb90Zmr9r2zQQz8P7SfmrOW_ZdIppM
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent
